service: secure-graphql

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-appsync-plugin

package:
  individually: true

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: false
    packager: "yarn"
  configFile: ${file(.env.${opt:stage, 'dev'}.yml):}
  resourceSlug: secure-graphql-${self:custom.configFile.STAGE}

provider:
  name: aws
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - xray:PutTelemetryRecords
            - xray:PutTraceSegments
          Resource: "*"
  runtime: nodejs20.x
  architecture: arm64
  stage: ${self:custom.configFile.STAGE}
  region: ${self:custom.configFile.REGION}
  environment:
    STAGE: ${self:custom.configFile.STAGE}

functions:
  - ${file(src/functions/functions.yml)}

appSync: ${file(src/api/api.yml)}

resources:
  - ${file(src/auth/auth.yml)}
  - ${file(src/database/database.yml)}
